#version 430 core

// specify local work group size
layout (local_size_x = 32, local_size_y = 32) in;

// specify image to clear
layout(binding = 0, r32ui) writeonly uniform uimage2D clear_image;

void main()
{
	// read x & y index of global invocation as index to write to
	ivec2 index = ivec2( gl_GlobalInvocationID.xy );
		
	// set clear color
	uvec4 clear_color = uvec4 ( 0, 0, 0, 0);
	
	// write into texture
	imageStore( clear_image, ivec2(index), clear_color );
}