#
# Try to find ANTTWEAKBAR library and include path.
# Once done this will define
#
# ANTTWEAKBAR_FOUND
# ANTTWEAKBAR_INCLUDE_PATH
# ANTTWEAKBAR_LIBRARY
# 

IF (MINGW)
	FIND_PATH( ANTTWEAKBAR_INCLUDE_PATH AntTweakBar.h
		${DEPENDENCIES_PATH}/AntTweakBar/include
	)

    FIND_LIBRARY( ANTTWEAKBAR_LIBRARY
        NAMES AntTweakBar
        PATHS
        ${DEPENDENCIES_PATH}/AntTweakBar/lib
    )

    execute_process(COMMAND ${CMAKE_COMMAND}  -E  copy_if_different
        ${DEPENDENCIES_PATH}/AntTweakBar/bin/AntTweakBar.dll
        ${PROJECT_BINARY_DIR}/bin/
    )

ELSEIF (MSVC)
    FIND_PATH( ANTTWEAKBAR_INCLUDE_PATH AntTweakBar.h
        ${DEPENDENCIES_PATH}/AntTweakBar/include
    )

    FIND_LIBRARY( ANTTWEAKBAR_LIBRARY
        NAMES AntTweakBar
        PATHS
        ${DEPENDENCIES_PATH}/AntTweakBar/lib
    )

    foreach (CONFIGURATION_TYPE ${CMAKE_CONFIGURATION_TYPES})
        execute_process(COMMAND ${CMAKE_COMMAND}  -E  copy_if_different
            ${DEPENDENCIES_PATH}/AntTweakBar/bin/AntTweakBar.dll
            ${PROJECT_BINARY_DIR}/bin/${CONFIGURATION_TYPE}/
        )
    endforeach()

ELSEIF(APPLE)

	FIND_PATH(ANTTWEAKBAR_INCLUDE_PATH AntTweakBar.h
	${DEPENDENCIES_PATH}/AntTweakBar/include)
	
	FIND_LIBRARY( ANTTWEAKBAR_LIBRARY
        NAMES libAntTweakBar.a
  		PATHS ${DEPENDENCIES_PATH}/AntTweakBar/lib)

ELSE()
	FIND_PATH(ANTTWEAKBAR_INCLUDE_PATH AntTweakBar.h)
	FIND_LIBRARY(ANTTWEAKBAR_LIBRARY
        NAMES AntTweakBar
	PATH_SUFFIXES dynamic) 
ENDIF ()



SET(ANTTWEAKBAR_FOUND "NO")
IF (ANTTWEAKBAR_INCLUDE_PATH AND ANTTWEAKBAR_LIBRARY)
	SET(ANTTWEAKBAR_LIBRARIES ${ANTTWEAKBAR_LIBRARY})
	SET(ANTTWEAKBAR_FOUND "YES")
    message("EXTERNAL LIBRARY 'ANTTWEAKBAR' FOUND")
    message("ANTTWEAKBAR_LIBRARY: " ${ANTTWEAKBAR_LIBRARY})
    message("ANTTWEAKBAR_INCLUDE_PATH: " ${ANTTWEAKBAR_INCLUDE_PATH})
ELSE()
    message("ERROR: EXTERNAL LIBRARY 'ANTTWEAKBAR' NOT FOUND")
ENDIF (ANTTWEAKBAR_INCLUDE_PATH AND ANTTWEAKBAR_LIBRARY)